import * as F from './files'

export default {
    '/node_modules/as-chain/index.ts': F.asChainIndex.default,
    '/node_modules/as-chain/action.ts': F.asChainAction.default,
    '/node_modules/as-chain/asset.ts': F.asChainAsset.default,
    '/node_modules/as-chain/bignum.ts': F.asChainBignum.default,
    '/node_modules/as-chain/crypto.ts': F.asChainCrypto.default,
    '/node_modules/as-chain/dbi64.ts': F.asChainDbi64.default,
    '/node_modules/as-chain/debug.ts': F.asChainDebug.default,
    '/node_modules/as-chain/decorator.ts': F.asChainDecorator.default,
    '/node_modules/as-chain/env.ts': F.asChainEnv.default,
    '/node_modules/as-chain/float128.ts': F.asChainFloat128.default,
    '/node_modules/as-chain/helpers.ts': F.asChainHelpers.default,
    '/node_modules/as-chain/idx64.ts': F.asChainIdx64.default,
    '/node_modules/as-chain/idx128.ts': F.asChainIdx128.default,
    '/node_modules/as-chain/idx256.ts': F.asChainIdx256.default,
    '/node_modules/as-chain/idxdb.ts': F.asChainIdxdb.default,
    '/node_modules/as-chain/idxf64.ts': F.asChainIdxf64.default,
    '/node_modules/as-chain/idxf128.ts': F.asChainIdxf128.default,
    '/node_modules/as-chain/mi.ts': F.asChainMi.default,
    '/node_modules/as-chain/name.ts': F.asChainName.default,
    '/node_modules/as-chain/serializer.ts': F.asChainSerializer.default,
    '/node_modules/as-chain/singleton.ts': F.asChainSingleton.default,
    '/node_modules/as-chain/system.ts': F.asChainSystem.default,
    '/node_modules/as-chain/time.ts': F.asChainTime.default,
    '/node_modules/as-chain/transaction.ts': F.asChainTransaction.default,
    '/node_modules/as-chain/utils.ts': F.asChainUtils.default,
    '/node_modules/as-chain/varint.ts': F.asChainVarint.default,
    '/node_modules/as-bignum/index.ts': F.asBignumIndex.default,
    '/node_modules/as-bignum/utils.ts': F.asBignumUtils.default,
    '/node_modules/as-bignum/globals.ts': F.asBignumGlobals.default,
    '/node_modules/as-bignum/integer/index.ts': F.asBignumIntegerIndex.default,
    '/node_modules/as-bignum/integer/i128.ts': F.asBignumIntegeri128.default,
    '/node_modules/as-bignum/integer/u128.ts': F.asBignumIntegeru128.default,
    '/node_modules/as-bignum/integer/i256.ts': F.asBignumIntegeri256.default,
    '/node_modules/as-bignum/integer/u256.ts': F.asBignumIntegeru256.default,
    '/node_modules/as-bignum/integer/safe/index.ts': F.asBignumIntegerSafeIndex.default,
    '/node_modules/as-bignum/integer/safe/i64.ts': F.asBignumIntegerSafei64.default,
    '/node_modules/as-bignum/integer/safe/i128.ts': F.asBignumIntegerSafei128.default,
    '/node_modules/as-bignum/integer/safe/i256.ts': F.asBignumIntegerSafei256.default,
    '/node_modules/as-bignum/integer/safe/u64.ts': F.asBignumIntegerSafeu64.default,
    '/node_modules/as-bignum/integer/safe/u128.ts': F.asBignumIntegerSafeu128.default,
    '/node_modules/as-bignum/integer/safe/u256.ts': F.asBignumIntegerSafeu256.default,
}